### ISSUE TITLE
Support different HTML elements

### ISSUE THREAD

**Issue by himynameisdave** [himynameisdave/svelte-flex#1]
If I want to add this flex to a `nav` element or an `article`, how could the library support that?

Taken from [this comment](https://www.reddit.com/r/sveltejs/comments/fw1vkl/svelteflex_a_simple_and_reusable_flexbox/fmm9cjs/).

**Comment by SeanMcP** [comment]
It looks like this isn't yet supported by Svelte: https://github.com/sveltejs/svelte/issues/2324

**Comment by demetrius-mp** [comment]
couldnt this be closed since its kinda duplicate of #28, and it is best described in there?

**Comment by himynameisdave** [comment]
Duplicate of https://github.com/himynameisdave/svelte-flex/issues/28
