### ISSUE TITLE
Support for Typescript?

### ISSUE THREAD

**Issue by erezsh** [himynameisdave/svelte-flex#35]
When trying to use Flex svelte from within typescript, I get this error:

```
Could not find a declaration file for module 'svelte-flex'. './node_modules/svelte-flex/lib/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/svelte-flex` if it exists or add a new declaration (.d.ts) file containing `declare module 'svelte-flex';`ts(7016)
```

Maybe I'm doing something wrong?

However, looking at the source, doesn't look like anything is typed.

**Comment by himynameisdave** [comment]
Typescript is supported as of [v2.0.0](https://github.com/himynameisdave/svelte-flex/releases/tag/v2.0.0), feel free to let us know if there is something specific which isn't working for you!
